package com.m2i.elearn.register;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.Resource;
import javax.mail.MessagingException;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceUnit;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.transaction.HeuristicMixedException;
import javax.transaction.HeuristicRollbackException;
import javax.transaction.NotSupportedException;
import javax.transaction.RollbackException;
import javax.transaction.SystemException;
import javax.transaction.UserTransaction;

import org.apache.commons.codec.digest.DigestUtils;
import org.mindrot.jbcrypt.BCrypt;

import com.m2i.elearn.jpa.UserJPA;

/**
 * Servlet implementation class RegisterFormServlet
 */
@WebServlet("/RegisterForm")
public class RegisterFormServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	private static final Logger LOGGER = Logger.getLogger(RegisterFormServlet.class.getName());

	@PersistenceUnit(unitName = "ELearningPU")
	private EntityManagerFactory emf;

	@Resource
	private UserTransaction utx;

	private static final String mail_user = "mailUser";
	private static final String password_user = "passwordUser";
	private static final String ATT_ERREURS = "erreurs";
	private static final String URL_HOME = "http://localhost:8080/elearn-webapp-0.1/welcome";

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		request.getRequestDispatcher("/WEB-INF/RegisterForm.jsp").forward(request, response);
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	@Override
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		Map<String, String> erreurs = new HashMap<String, String>();

		String mailUser = request.getParameter("mailUser");
		String passwordUser = request.getParameter("passwordUser");

		LOGGER.info(String.format("Received mail_user=%s password_user=%s",  mailUser, passwordUser));

		EntityManager em2 = emf.createEntityManager();
		UserJPA userF = null;

		String mailUserF = "F"+ mailUser;
		LOGGER.info(String.format("Check mailUser %s exist ?", mailUserF));

		// Checking if the given mail is already used
		try{
			userF =	em2.createQuery("SELECT u FROM UserJPA u WHERE u.mailUser = :mailUser", UserJPA.class)
					.setParameter("mailUser", mailUserF).getSingleResult();
		} catch (NoResultException e){
			// Mail not already used by someone else
		};

		if (userF != null){
			erreurs.put( mail_user, "An existing user is already using this email adress.");
			request.setAttribute( ATT_ERREURS, erreurs );
			request.getRequestDispatcher("/WEB-INF/RegisterForm.jsp").forward(request, response);
			return;
		}

		UserJPA user = new UserJPA();
		// The id of the user will be auto generated by the database
		user.setMailUser("F"+mailUser);
		
		// Encryption of password using Bcrypt
		String passwordUserCrypt = BCrypt.hashpw(passwordUser, BCrypt.gensalt(12));
		user.setPasswordUser(passwordUserCrypt);
		LOGGER.info(String.format(" User %s, password %s, passwordBcrypt %s",mailUser,passwordUser,passwordUserCrypt));

		// Encryption of confirmation key sent by mail
		String md5 = DigestUtils.md5Hex(mailUser);
		user.setConfirmedKeyUser(md5);
		LOGGER.info(" User/key " + mailUser + "/key:"+ md5);

		// Mail validation
		Mail mailConfirm = null;
		try {
			validationMailUser(mailUser);
		} catch (Exception e) {
			erreurs.put( mail_user, e.getMessage());
		}
		// Password validation
		try {   
			validationPasswordUser(passwordUser);
		} catch (Exception e) {
			erreurs.put(password_user, e.getMessage());
		}

		// Put result and error in the request object
		request.setAttribute(ATT_ERREURS, erreurs);

		if (!erreurs.isEmpty()) {
			request.getRequestDispatcher("/WEB-INF/RegisterForm.jsp").forward(request, response);
			return;
		};

		LOGGER.info(" Before Save UserJPA -->"+user);

		try {
			utx.begin();
			EntityManager em = emf.createEntityManager();
			em.joinTransaction();
			em.persist(user);

			mailConfirm = new Mail(mailUser,
					"Validate your registration as a trainer",
					"Hi, please use the following link to confirm your elearning account : \n "
							+ "http://localhost:8080/elearn-webapp-0.1/receivemail?id="+mailUser
							+ "&key="+user.getConfirmedKeyUser());
			mailConfirm.sendMail();

			utx.commit();
			LOGGER.info(String.format("User Saved mailUser=%s" , mailUser));

			response.sendRedirect(URL_HOME);
			return;

		} catch (NotSupportedException | SystemException | SecurityException | IllegalStateException | RollbackException
				| HeuristicMixedException | HeuristicRollbackException | MessagingException e) {
			LOGGER.log(Level.INFO, "Transaction failed", e);
			response.sendError(500, "Server error");

			try {
				utx.rollback();
				LOGGER.info(String.format("RollBack %s" , mailUser));
			} catch (IllegalStateException 	| SecurityException | SystemException e1) {
				LOGGER.log(Level.INFO, "Transaction rollback failed", e1);
				response.sendError(500, "Server error");
			}
		}

		LOGGER.info(String.format("Problem... Redirect... %s" , "/"));

		response.sendRedirect("/RegisterForm");
	}
	private void validationMailUser(String mailUser) throws Exception {
		if (mailUser == null){
			throw new Exception("Please enter a valid email address.");
		}
		if (!mailUser.matches("([^.@]+)(\\.[^.@]+)*@([^.@]+\\.)+([^.@]+)")) {
			throw new Exception("Please enter a valid email address.");
		}
	} 

	private void validationPasswordUser(String passwordUser) throws Exception {

		boolean Error = false;
		String Message = "";
		if (passwordUser != null && passwordUser.trim().length() < 8 ) {
			Error=true;
			Message += " 8 letters";
		}
		if (!passwordUser.matches("[^A-Z]*[A-Z]+[^A-Z]*")) {
			Error=true;
			Message += " an uppercase";	
		}	
		if (!passwordUser.matches("[^0-9]*[0-9]+[^0-9]*")) {
			Error=true;
			Message += " a number";
		}
		if (Error) {
			throw new Exception("Your password must contain at least :"+ Message);
		}	
	}
}